"""Writes js2/art_valley.js: the valley's new ground and scenery, and keeps
the manifest honest. Run it from anywhere: python3 tools/valley/build.py"""
import os, sys, json
D = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(D, '..', '..'))
sys.path.insert(0, D)
import tiles, props

def emit(name, frames, outline):
    body = ',\n'.join('[\n' + ',\n'.join("'%s'" % r for r in f) + ']' for f in frames)
    return "SPRITES.%s = { %sframes: [\n%s]};\n" % (name, 'outline: true, ' if outline else '', body)

T = tiles.build(); P = props.build()
out = ["""'use strict';
// art_valley.js - the valley, remade. GENERATED by tools/valley/build.py -
// edit the generators, not this file. Tiles are seamless 32x32 with no
// outline; scenery is drawn at the size the people need and gets the ink.

"""]
for k, v in T.items(): out.append(emit(k, v, False))
for k, v in P.items(): out.append(emit(k, v, True))
open(os.path.join(ROOT, 'js2/art_valley.js'), 'w').write('\n'.join(out))
man = json.load(open(os.path.join(ROOT, 'js2/manifest.json')))
for k, v in list(T.items()) + list(P.items()):
    man[k] = dict(w=len(v[0][0]), h=len(v[0]), frames=len(v), file='art_valley',
                  note=man.get(k, {}).get('note', 'valley scenery'))
json.dump(man, open(os.path.join(ROOT, 'js2/manifest.json'), 'w'), indent=1)
print('wrote %d tiles and %d props' % (len(T), len(P)))
