// ---------------------------------------------------------------------------
// heroes.js - the Rockbottoms: four people, four instruments, four ways to
// play. Whoever you pick is the one who was in the toilet when Grandma Rex
// came; the other three are the ones she carried off.
//
// Each hero has
//   - a body and a sprite set (base), and a colour the interface wears
//   - a way of fighting (mechanic): RAGE, ECHO, BEAT or the ELEMENTS
//   - a way of moving round the board (ability)
//   - a starter deck, a starter artifact and their own pool of cards
//   - a band passive, for when they have been rescued and are backing
//     somebody else up
// ---------------------------------------------------------------------------
'use strict';

const HEROES = {
  bronk: {
    id: 'bronk', name: 'BRONK', title: 'The Dad', base: 'bronk', hp: 100, hand: 5, energy: 3,
    color: '#ff8a3a', dark: '#7d1d2b', light: '#ffd0a0',
    instrument: 'the Rib-Axe', instrumentDesc: 'a guitar strung across a mammoth ribcage',
    blurb: 'Big, loud and permanently hungry. Bronk loves his family more than he loves lunch, which is saying a lot.',
    mechanic: { name: 'RAGE', desc: 'Every time Bronk is hurt he gets angrier: each {r}Rage{/} adds 1 to his attacks. Some cards burn all of it at once.' },
    ability: { id: 'heavy', name: 'HEAVY STEP', desc: 'After you roll you can walk {y}one tile fewer{/}. Food tiles heal him {g}double{/}.' },
    deck: ['power_chord', 'power_chord', 'power_chord', 'power_chord', 'stone_wall', 'stone_wall', 'stone_wall', 'stone_wall', 'belly_bump', 'headbutt'],
    relic: 'rib_axe',
    band: { name: 'BIG HUG', desc: 'Bronk starts every fight by hugging you. {b}+8 Block{/}.' },
    rescued: 'Dad! You came! I knew you would come. I ate all the snacks.',
  },
  vela: {
    id: 'vela', name: 'VELA', title: 'The Mum', base: 'vela', hp: 80, hand: 5, energy: 3,
    color: '#ff7ab8', dark: '#58203c', light: '#ffd0e4',
    instrument: 'the Tusk Horn', instrumentDesc: 'a mammoth tusk, hollowed out and very, very loud',
    blurb: 'The real boss of the cave. Sharp as flint, tough as a tusk, and she has a look that can stop a triceratops.',
    mechanic: { name: 'ECHO', desc: 'Horn cards {c}echo{/}: a free half-strength copy comes back next turn. She controls fights with {o}Weak{/}, {o}Vulnerable{/} and Block.' },
    ability: { id: 'steady', name: 'STEADY HAND', desc: 'After every roll you can make it {y}one more or one less{/}. Mystery tiles near you show what they hold.' },
    deck: ['horn_blast', 'horn_blast', 'horn_blast', 'horn_blast', 'stone_wall', 'stone_wall', 'stone_wall', 'stone_wall', 'the_look', 'tidy_up'],
    relic: 'sabre_pendant',
    band: { name: 'THE LOOK', desc: 'Every turn, Vela glares at a random beast: {o}1 Weak{/}.' },
    rescued: 'About time. Now, which one of these lizards do I have to have a word with?',
  },
  pebble: {
    id: 'pebble', name: 'PEBBLE', title: 'The Son', base: 'kid_a', hp: 64, hand: 6, energy: 3,
    color: '#a8e878', dark: '#27632f', light: '#e0ffc8',
    instrument: 'the Skull Bongos', instrumentDesc: 'two skulls with hide stretched over them. He will not say whose.',
    blurb: 'Nine years old and made entirely of sugar. Drums on everything, is scared of nothing, has never once walked anywhere.',
    mechanic: { name: 'BEAT', desc: 'Pebble plays lots of cheap cards fast. His {y}Beat{/} is how many cards he has played this turn, and most of his cards get better with it.' },
    ability: { id: 'sugar', name: 'SUGAR RUSH', desc: 'Rolls {y}two dice{/} every time and picks one. Roll a double and he gets {y}another go{/}.' },
    deck: ['tap_tap', 'tap_tap', 'tap_tap', 'tap_tap', 'duck_cover', 'duck_cover', 'duck_cover', 'drumroll', 'drumroll', 'sugar_high'],
    relic: 'skull_bongos',
    band: { name: 'DRUM BACKUP', desc: 'Every turn Pebble hits a random beast: {y}3 damage{/}, more in later lands.' },
    rescued: 'THAT WAS AMAZING. Can we do it again? Not the being carried off bit. The rest.',
  },
  roxy: {
    id: 'roxy', name: 'ROXY', title: 'The Daughter', base: 'kid_b', hp: 70, hand: 5, energy: 3,
    color: '#86e8d2', dark: '#18706a', light: '#d0fff4',
    instrument: 'the Bone Flute', instrumentDesc: 'carved from a crane\'s leg. The weather listens when she plays it.',
    blurb: 'Fifteen, furious, and a little bit magic. Talks to storms. Rolls her eyes at everything, including you.',
    mechanic: { name: 'ELEMENTS', desc: '{b}Water{/} Soaks beasts, and {y}Lightning{/} does double to a Soaked beast. {o}Fire{/} burns, {c}Wind{/} keeps her moving.' },
    ability: { id: 'rain', name: 'RAIN DANCE', desc: 'Make the ground near you {b}wet{/}. Recharges after 3 rolls. She starts with {y}Wet Feet{/}.' },
    deck: ['splash', 'splash', 'splash', 'zap', 'zap', 'zap', 'gust', 'gust', 'gust', 'spark'],
    relic: 'wet_feet',
    band: { name: 'HEALING SONG', desc: 'Roxy plays after every fight: {g}heal 5{/}. Riff timing is a little kinder.' },
    rescued: 'Ugh. Fine. Thank you. Don\'t make it weird.',
  },
};
const HERO_ORDER = ['bronk', 'vela', 'pebble', 'roxy'];

const Heroes = {
  get(id) { return HEROES[id] || HEROES.bronk; },
  cur() { return this.get(Game.run && Game.run.hero); },
  // the other three, in the order the bosses hold them
  // who has a seat at the table: Bronk always; each rescue won opens the next
  unlocked() { const u = Settings.unlocked || []; return HERO_ORDER.filter(id => id === 'bronk' || u.includes(id)); },
  isUnlocked(id) { return this.unlocked().includes(id); },
  unlockNext() {
    const u = this.unlocked(), next = HERO_ORDER.find(id => !u.includes(id));
    if (!next) return null;
    Settings.unlocked = u.concat(next); Game.saveSettings();
    return next;
  },
  captives(id) { return ['pebble', 'roxy', 'vela', 'bronk'].filter(k => k !== id); },
  spr(id, clip = 'idle') { const b = this.get(id).base; return b + '_' + clip; },
  has(id, clip) { return !!SPRITES[this.get(id).base + '_' + clip]; },
};

// ------------------------------------------------------------------ cards
// Every hero's own cards. They join CARDS with `hero` set, so the reward pool
// only ever deals you your own and the family's shared ones.
Object.assign(CARDS, {
  // ================================================================ BRONK
  belly_bump: { hero: 'bronk', name: 'Belly Bump', type: 'attack', cost: 1, rarity: 'starter', art: 'art_foot', target: 'enemy',
    v: { dmg: 6, block: 4 }, up: v => { v.dmg = 8; v.block = 6; },
    desc: (v, c) => `Deal {y}${Cards.dmg(v.dmg, c)}{/}. Gain {b}${v.block}{/} Block and {r}1 Rage{/}.`,
    effect: function* (c, card, t) { yield* c.dealDamage(t, card.v.dmg); c.gainBlock(card.v.block); c.gainRage(1); } },
  headbutt: { hero: 'bronk', name: 'Headbutt', type: 'attack', cost: 1, rarity: 'starter', art: 'art_skull', target: 'enemy',
    v: { dmg: 9, vuln: 2 }, up: v => { v.dmg = 12; },
    desc: (v, c) => `Deal {y}${Cards.dmg(v.dmg, c)}{/}. With {r}3+ Rage{/}, apply {o}${v.vuln}{/} Vulnerable.`,
    effect: function* (c, card, t) { yield* c.dealDamage(t, card.v.dmg, { heavy: true }); if (t.alive && c.rage >= 3) c.applyEnemy(t, 'vuln', card.v.vuln); } },
  rage_riff: { hero: 'bronk', name: 'Rage Riff', type: 'attack', cost: 2, rarity: 'common', art: 'art_bolt', target: 'enemy', riff: RIFF.med,
    v: { dmg: 9, per: 2 }, up: v => { v.dmg = 12; v.per = 3; },
    desc: (v, c) => `Riff. Deal {y}${Cards.dmg(v.dmg, c)}{/}, +${v.per} per {r}Rage{/}.`,
    effect: function* (c, card, t, r) { yield* c.dealDamage(t, c.riffDamage(card, r, card.v.dmg + card.v.per * c.rage), { heavy: true }); } },
  belly_flop: { hero: 'bronk', name: 'Belly Flop', type: 'attack', cost: 1, rarity: 'common', art: 'art_foot', target: 'all',
    v: { dmg: 8, self: 3 }, up: v => { v.dmg = 11; },
    desc: (v, c) => `Deal {y}${Cards.dmg(v.dmg, c)}{/} to ALL. Lose {r}${v.self}{/} HP (that is Rage).`,
    effect: function* (c, card) { Juice.shake(10, 0.4); yield* c.dealAll(card.v.dmg); c.selfHarm(card.v.self); } },
  tantrum: { hero: 'bronk', name: 'Tantrum', type: 'skill', cost: 1, rarity: 'common', art: 'art_fire', target: 'self',
    v: { rage: 3, block: 3 }, up: v => { v.rage = 4; v.block = 6; },
    desc: v => `Gain {r}${v.rage} Rage{/} and {b}${v.block}{/} Block.`,
    effect: function* (c, card) { c.gainRage(card.v.rage); c.gainBlock(card.v.block); AudioSys.sfx('roar', { pitch: 110, vol: 0.5, len: 0.5 }); yield 0.2; } },
  bone_breaker: { hero: 'bronk', name: 'Bone Breaker', type: 'attack', cost: 2, rarity: 'uncommon', art: 'art_club', target: 'enemy',
    v: { dmg: 8, per: 4 }, up: v => { v.per = 6; },
    desc: (v, c) => `Deal {y}${v.dmg}{/}, +${v.per} per {r}Rage{/}${c ? ` ({y}${c.previewDamage(v.dmg + v.per * c.rage) - c.rage}{/})` : ''}. Lose all Rage.`,
    effect: function* (c, card, t) { const n = c.rage; c.rage = 0; yield* c.dealDamage(t, card.v.dmg + card.v.per * n, { heavy: true, noRage: true }); } },
  thick_skull: { hero: 'bronk', name: 'Thick Skull', type: 'skill', cost: 1, rarity: 'common', art: 'art_shield', target: 'self',
    v: { block: 8, more: 8 }, up: v => { v.block = 10; },
    desc: v => `Gain {b}${v.block}{/} Block. With {r}5+ Rage{/}, {b}${v.more}{/} more.`,
    effect: function* (c, card) { c.gainBlock(card.v.block + (c.rage >= 5 ? card.v.more : 0)); yield 0.12; } },
  second_helping: { hero: 'bronk', name: 'Second Helping', type: 'skill', cost: 1, rarity: 'common', art: 'art_meat', target: 'self', exhaust: true,
    v: { heal: 6, rage: 2 }, up: v => { v.heal = 9; },
    desc: v => `Heal {g}${v.heal}{/}. Gain {r}${v.rage} Rage{/}. Exhaust.`,
    effect: function* (c, card) { c.heal(card.v.heal); c.gainRage(card.v.rage); AudioSys.sfx('chomp'); yield 0.2; } },
  dad_roar: { hero: 'bronk', name: 'Dad Roar', type: 'skill', cost: 1, rarity: 'uncommon', art: 'art_horn', target: 'all',
    v: { weak: 1, rage: 2 }, up: v => { v.weak = 2; },
    desc: v => `Apply {o}${v.weak}{/} Weak to ALL. Gain {r}${v.rage} Rage{/}.`,
    effect: function* (c, card) { AudioSys.sfx('roar', { pitch: 90, vol: 0.7, len: 0.8 }); Juice.shake(8, 0.4); for (const e of c.alive()) c.applyEnemy(e, 'weak', card.v.weak); c.gainRage(card.v.rage); yield 0.3; } },
  club_solo: { hero: 'bronk', name: 'Club Solo', type: 'attack', cost: 2, rarity: 'common', art: 'art_club', target: 'enemy', riff: RIFF.long,
    v: { dmg: 6, hits: 3 }, up: v => { v.dmg = 8; },
    desc: (v, c) => `Long riff. Deal {y}${Cards.dmg(v.dmg, c)}{/} ${v.hits} times.`,
    effect: function* (c, card, t, r) { for (let i = 0; i < card.v.hits; i++) { yield* c.dealDamage(t, c.riffDamage(card, r), { quick: true }); if (!t.alive) break; } } },
  stomp: { hero: 'bronk', name: 'Stomp', type: 'attack', cost: 1, rarity: 'common', art: 'art_foot', target: 'all', terrain: 'stone',
    v: { dmg: 6, bonus: 5 }, up: v => { v.dmg = 8; },
    desc: (v, c) => `Deal {y}${Cards.dmg(v.dmg, c)}{/} to ALL. {s}Touched stone this round:{/} +${v.bonus}.`,
    effect: function* (c, card) { yield* c.dealAll(card.v.dmg + (c.touchedAny('stone') ? card.v.bonus : 0)); } },
  bone_crusher: { hero: 'bronk', name: 'Bone Crusher', type: 'attack', cost: 1, rarity: 'uncommon', art: 'art_skull', target: 'enemy', terrain: 'bone',
    v: { dmg: 11, rage: 3 }, up: v => { v.dmg = 15; },
    desc: (v, c) => `Deal {y}${Cards.dmg(v.dmg, c)}{/}. {s}Touched bones this round:{/} gain {r}${v.rage} Rage{/} first.`,
    effect: function* (c, card, t) { if (c.touchedAny('bone')) c.gainRage(card.v.rage); yield* c.dealDamage(t, card.v.dmg, { heavy: true }); } },
  mud_slide: { hero: 'bronk', name: 'Mud Slide', type: 'skill', cost: 1, rarity: 'common', art: 'art_wave', target: 'self', terrain: 'wet',
    v: { block: 7, draw: 2 }, up: v => { v.block = 10; },
    desc: v => `Gain {b}${v.block}{/} Block. {s}Touched water this round:{/} draw ${v.draw}.`,
    effect: function* (c, card) { c.gainBlock(card.v.block); if (c.touchedAny('wet')) c.drawCards(card.v.draw); yield 0.12; } },
  unstoppable: { hero: 'bronk', name: 'Unstoppable', type: 'power', cost: 1, rarity: 'uncommon', art: 'art_shield', target: 'self',
    v: { block: 2 }, up: v => { v.block = 3; },
    desc: v => `Whenever you gain {r}Rage{/}, gain {b}${v.block}{/} Block per point.`,
    effect: function* (c, card) { c.addPower('unstop', card.v.block); yield 0.2; } },
  hungry: { hero: 'bronk', name: 'Always Hungry', type: 'power', cost: 1, rarity: 'uncommon', art: 'art_meat', target: 'self',
    v: { heal: 6 }, up: v => { v.heal = 9; },
    desc: v => `When this fight ends, heal {g}${v.heal}{/}.`,
    effect: function* (c, card) { c.addPower('hungry', card.v.heal); yield 0.2; } },
  heavy_metal: { hero: 'bronk', name: 'Heavy Metal', type: 'attack', cost: 3, rarity: 'rare', art: 'art_strum', target: 'enemy', riff: RIFF.epic,
    v: { dmg: 26, per: 3 }, up: v => { v.dmg = 34; },
    desc: (v, c) => `Epic riff. Deal {y}${Cards.dmg(v.dmg, c)}{/}, +${v.per} per {r}Rage{/}.`,
    effect: function* (c, card, t, r) { Juice.flash('#ffa832', 0.5, 3); yield* c.dealDamage(t, c.riffDamage(card, r, card.v.dmg + card.v.per * c.rage), { heavy: true }); } },
  dad_joke: { hero: 'bronk', name: 'Dad Joke', type: 'skill', cost: 0, rarity: 'rare', art: 'art_crowd', target: 'all', exhaust: true,
    v: { stun: 1 }, up: v => { v.noExhaust = true; },
    desc: v => `Every beast is {c}Stunned{/} for a turn, from pure embarrassment.${v.noExhaust ? '' : ' Exhaust.'}`,
    effect: function* (c, card) { for (const e of c.alive()) c.stun(e, card.v.stun); AudioSys.sfx('stun'); yield 0.4; } },

  // ================================================================= VELA
  horn_blast: { hero: 'vela', name: 'Horn Blast', type: 'attack', cost: 1, rarity: 'starter', art: 'art_horn', target: 'enemy', riff: RIFF.easy, echo: true,
    v: { dmg: 6 }, up: v => { v.dmg = 9; },
    desc: (v, c) => `Riff. Deal {y}${Cards.dmg(v.dmg, c)}{/}. {c}Echo.{/}`,
    effect: function* (c, card, t, r) { yield* c.dealDamage(t, c.riffDamage(card, r)); } },
  the_look: { hero: 'vela', name: 'The Look', type: 'skill', cost: 1, rarity: 'starter', art: 'art_skull', target: 'enemy',
    v: { weak: 2, vuln: 0 }, up: v => { v.vuln = 1; },
    desc: v => `Apply {o}${v.weak}{/} Weak${v.vuln ? ` and {o}${v.vuln}{/} Vulnerable` : ''}.`,
    effect: function* (c, card, t) { c.applyEnemy(t, 'weak', card.v.weak); if (card.v.vuln) c.applyEnemy(t, 'vuln', card.v.vuln); yield 0.2; } },
  tidy_up: { hero: 'vela', name: 'Tidy Up', type: 'skill', cost: 1, rarity: 'starter', art: 'art_shield', target: 'self',
    v: { block: 5, draw: 1 }, up: v => { v.block = 8; },
    desc: v => `Gain {b}${v.block}{/} Block. Draw ${v.draw}.`,
    effect: function* (c, card) { c.gainBlock(card.v.block); c.drawCards(card.v.draw); yield 0.12; } },
  mammoth_call: { hero: 'vela', name: 'Mammoth Call', type: 'skill', cost: 2, rarity: 'common', art: 'art_horn', target: 'all', echo: true,
    v: { vuln: 2 }, up: v => { v.cost = 1; },
    desc: v => `Apply {o}${v.vuln}{/} Vulnerable to ALL. {c}Echo.{/}`,
    effect: function* (c, card) { AudioSys.sfx('roar', { pitch: 70, vol: 0.5, len: 0.9 }); for (const e of c.alive()) c.applyEnemy(e, 'vuln', card.v.vuln); yield 0.3; } },
  stern_word: { hero: 'vela', name: 'Stern Word', type: 'skill', cost: 0, rarity: 'common', art: 'art_note', target: 'enemy', echo: true,
    v: { weak: 1 }, up: v => { v.weak = 2; },
    desc: v => `Apply {o}${v.weak}{/} Weak. {c}Echo.{/}`,
    effect: function* (c, card, t) { c.applyEnemy(t, 'weak', card.v.weak); yield 0.15; } },
  deafening: { hero: 'vela', name: 'Deafening Note', type: 'attack', cost: 2, rarity: 'uncommon', art: 'art_horn', target: 'enemy', riff: RIFF.med, terrain: 'dark',
    v: { dmg: 12 }, up: v => { v.dmg = 16; },
    desc: (v, c) => `Riff. Deal {y}${Cards.dmg(v.dmg, c)}{/}. {s}Touched a cave this round:{/} {c}Stun{/} it.`,
    effect: function* (c, card, t, r) { yield* c.dealDamage(t, c.riffDamage(card, r), { heavy: true }); if (t.alive && c.touchedAny('dark')) c.stun(t, 1); } },
  guard_cave: { hero: 'vela', name: 'Guard the Cave', type: 'skill', cost: 1, rarity: 'common', art: 'art_shield', target: 'self', terrain: 'stone',
    v: { block: 9, bonus: 5 }, up: v => { v.block = 12; },
    desc: v => `Gain {b}${v.block}{/} Block. {s}Touched stone this round:{/} +${v.bonus}.`,
    effect: function* (c, card) { c.gainBlock(card.v.block + (c.touchedAny('stone') ? card.v.bonus : 0)); yield 0.12; } },
  shield_wall: { hero: 'vela', name: 'Shield Wall', type: 'skill', cost: 2, rarity: 'uncommon', art: 'art_shield', target: 'self',
    v: { block: 18 }, up: v => { v.block = 24; },
    desc: v => `Gain {b}${v.block}{/} Block.`,
    effect: function* (c, card) { c.gainBlock(card.v.block); yield 0.12; } },
  resonance: { hero: 'vela', name: 'Resonance', type: 'attack', cost: 1, rarity: 'uncommon', art: 'art_wave', target: 'enemy',
    v: { per: 5 }, up: v => { v.per = 7; },
    desc: v => `Deal {y}${v.per}{/} for every Weak and Vulnerable on it.`,
    effect: function* (c, card, t) { const n = (t.st.weak || 0) + (t.st.vuln || 0); yield* c.dealDamage(t, Math.max(2, card.v.per * n), { heavy: n > 2 }); } },
  wind_chime: { hero: 'vela', name: 'Wind Chime', type: 'skill', cost: 1, rarity: 'common', art: 'art_note', target: 'self', echo: true,
    v: { draw: 2 }, up: v => { v.draw = 3; },
    desc: v => `Draw ${v.draw}. {c}Echo.{/}`,
    effect: function* (c, card) { c.drawCards(card.v.draw); yield 0.12; } },
  lullaby_horn: { hero: 'vela', name: 'Low Hum', type: 'skill', cost: 1, rarity: 'uncommon', art: 'art_moon', target: 'enemy', exhaust: true,
    v: { stun: 1 }, up: v => { v.noExhaust = true; },
    desc: v => `{c}Stun{/} a beast.${v.noExhaust ? '' : ' Exhaust.'}`,
    effect: function* (c, card, t) { c.stun(t, card.v.stun); AudioSys.sfx('stun'); yield 0.3; } },
  echo_chamber: { hero: 'vela', name: 'Echo Chamber', type: 'power', cost: 2, rarity: 'rare', art: 'art_spiral', target: 'self',
    v: {}, up: v => { v.cost = 1; },
    desc: () => `Echoes come back at {c}full strength{/}.`,
    effect: function* (c, card) { c.addPower('fullEcho', 1); yield 0.2; } },
  mothering: { hero: 'vela', name: 'Motherly Instinct', type: 'power', cost: 1, rarity: 'uncommon', art: 'art_heart', target: 'self',
    v: { block: 3 }, up: v => { v.block = 5; },
    desc: v => `Start of turn: gain {b}${v.block}{/} Block.`,
    effect: function* (c, card) { c.addPower('mother', card.v.block); yield 0.2; } },
  cave_echo: { hero: 'vela', name: 'Cave Echo', type: 'attack', cost: 1, rarity: 'common', art: 'art_wave', target: 'enemy', echo: true, terrain: 'dark',
    v: { dmg: 7, bonus: 5 }, up: v => { v.dmg = 10; },
    desc: (v, c) => `Deal {y}${Cards.dmg(v.dmg, c)}{/}. {s}Touched a cave:{/} +${v.bonus}. {c}Echo.{/}`,
    effect: function* (c, card, t) { yield* c.dealDamage(t, card.v.dmg + (c.touchedAny('dark') ? card.v.bonus : 0)); } },
  last_word: { hero: 'vela', name: 'The Last Word', type: 'attack', cost: 3, rarity: 'rare', art: 'art_horn', target: 'all', riff: RIFF.epic,
    v: { dmg: 22 }, up: v => { v.dmg = 30; },
    desc: (v, c) => `Epic riff. Deal {y}${Cards.dmg(v.dmg, c)}{/} to ALL. Beasts with Weak take half again.`,
    effect: function* (c, card, t, r) { const d = c.riffDamage(card, r); Juice.flash('#ffb0cf', 0.5, 3); for (const e of c.alive()) c.damageEnemy(e, c.calcDamage(e.st.weak > 0 ? Math.round(d * 1.5) : d, e), { heavy: true }); AudioSys.sfx('bighit'); Juice.shake(12, 0.5); yield 0.4; } },

  // =============================================================== PEBBLE
  tap_tap: { hero: 'pebble', name: 'Tap Tap', type: 'attack', cost: 1, rarity: 'starter', art: 'art_drum', target: 'enemy',
    v: { dmg: 3, hits: 2 }, up: v => { v.hits = 3; },
    desc: (v, c) => `Deal {y}${Cards.dmg(v.dmg, c)}{/} ${v.hits} times.`,
    effect: function* (c, card, t) { for (let i = 0; i < card.v.hits; i++) { yield* c.dealDamage(t, card.v.dmg, { quick: true }); if (!t.alive) break; } } },
  duck_cover: { hero: 'pebble', name: 'Duck and Cover', type: 'skill', cost: 1, rarity: 'starter', art: 'art_shield', target: 'self',
    v: { block: 5 }, up: v => { v.block = 8; },
    desc: v => `Gain {b}${v.block}{/} Block.`,
    effect: function* (c, card) { c.gainBlock(card.v.block); yield 0.1; } },
  drumroll: { hero: 'pebble', name: 'Drumroll', type: 'attack', cost: 0, rarity: 'starter', art: 'art_drum', target: 'enemy',
    v: { dmg: 2, draw: 1 }, up: v => { v.dmg = 4; },
    desc: (v, c) => `Deal {y}${Cards.dmg(v.dmg, c)}{/}. Draw ${v.draw}.`,
    effect: function* (c, card, t) { yield* c.dealDamage(t, card.v.dmg, { quick: true }); c.drawCards(card.v.draw); } },
  sugar_high: { hero: 'pebble', name: 'Sugar High', type: 'skill', cost: 0, rarity: 'starter', art: 'art_star', target: 'self', exhaust: true,
    v: { energy: 1, draw: 1 }, up: v => { v.energy = 2; },
    desc: v => `Gain {c}${v.energy}{/} Energy. Draw ${v.draw}. Exhaust.`,
    effect: function* (c, card) { c.gainEnergy(card.v.energy); c.drawCards(card.v.draw); yield 0.12; } },
  flurry: { hero: 'pebble', name: 'Flurry', type: 'attack', cost: 1, rarity: 'common', art: 'art_drum', target: 'enemy',
    v: { dmg: 2 }, up: v => { v.dmg = 3; },
    desc: (v, c) => `Deal {y}${Cards.dmg(v.dmg, c)}{/} once, plus once per card played before it this turn${c ? ` (${c.played + 1} hits)` : ''}.`,
    effect: function* (c, card, t) { const n = c.played; for (let i = 0; i < n; i++) { yield* c.dealDamage(t, card.v.dmg, { quick: true }); if (!t.alive) break; } } },
  big_finish: { hero: 'pebble', name: 'Big Finish', type: 'attack', cost: 2, rarity: 'uncommon', art: 'art_star', target: 'enemy', riff: RIFF.med,
    v: { per: 5 }, up: v => { v.per = 7; },
    desc: (v, c) => `Riff. Deal {y}${v.per}{/} per card played this turn${c ? ` ({y}${v.per * (c.played + 1)}{/})` : ''}.`,
    effect: function* (c, card, t, r) { yield* c.dealDamage(t, c.riffDamage(card, r, card.v.per * c.played), { heavy: true }); } },
  snack_time: { hero: 'pebble', name: 'Snack Time', type: 'skill', cost: 0, rarity: 'common', art: 'art_meat', target: 'self',
    v: { heal: 2, draw: 1 }, up: v => { v.heal = 4; },
    desc: v => `Heal {g}${v.heal}{/}. Draw ${v.draw}.`,
    effect: function* (c, card) { c.heal(card.v.heal); c.drawCards(card.v.draw); AudioSys.sfx('chomp'); yield 0.12; } },
  paradiddle: { hero: 'pebble', name: 'Paradiddle', type: 'attack', cost: 1, rarity: 'common', art: 'art_drum', target: 'enemy', riff: RIFF.easy,
    v: { dmg: 3, hits: 4 }, up: v => { v.dmg = 4; },
    desc: (v, c) => `Riff. Deal {y}${Cards.dmg(v.dmg, c)}{/} ${v.hits} times.`,
    effect: function* (c, card, t, r) { for (let i = 0; i < card.v.hits; i++) { yield* c.dealDamage(t, c.riffDamage(card, r), { quick: true }); if (!t.alive) break; } } },
  hide_seek: { hero: 'pebble', name: 'Hide and Seek', type: 'skill', cost: 1, rarity: 'common', art: 'art_foot', target: 'self', terrain: 'grass',
    v: { block: 7, draw: 1 }, up: v => { v.block = 10; },
    desc: v => `Gain {b}${v.block}{/} Block. {s}Touched grass this round:{/} draw ${v.draw} and it costs 0 next time.`,
    effect: function* (c, card) { c.gainBlock(card.v.block); if (c.touchedAny('grass')) c.drawCards(card.v.draw); yield 0.1; } },
  pebble_toss: { hero: 'pebble', name: 'Pebble Toss', type: 'attack', cost: 0, rarity: 'common', art: 'art_boulder', target: 'enemy',
    v: { dmg: 4 }, up: v => { v.dmg = 6; },
    desc: (v, c) => `Deal {y}${Cards.dmg(v.dmg, c)}{/}. No riff, just a rock.`,
    effect: function* (c, card, t) { yield* c.dealDamage(t, card.v.dmg, { projectile: true }); } },
  cartwheel: { hero: 'pebble', name: 'Cartwheel', type: 'skill', cost: 0, rarity: 'common', art: 'art_spiral', target: 'self',
    v: { block: 3, draw: 1 }, up: v => { v.block = 5; },
    desc: v => `Gain {b}${v.block}{/} Block. Draw ${v.draw}.`,
    effect: function* (c, card) { c.gainBlock(card.v.block); c.drawCards(card.v.draw); yield 0.1; } },
  bug_friend: { hero: 'pebble', name: 'Bug Friend', type: 'power', cost: 1, rarity: 'uncommon', art: 'art_star', target: 'self',
    v: { dmg: 3 }, up: v => { v.dmg = 5; },
    desc: v => `His pet beetle helps. Start of turn: {y}${v.dmg}{/} damage to a random beast.`,
    effect: function* (c, card) { c.addPower('bug', card.v.dmg); yield 0.2; } },
  rhythm_kid: { hero: 'pebble', name: 'Rhythm Kid', type: 'power', cost: 2, rarity: 'uncommon', art: 'art_note', target: 'self',
    v: { block: 1 }, up: v => { v.block = 2; },
    desc: v => `Every card you play gives {b}${v.block}{/} Block.`,
    effect: function* (c, card) { c.addPower('rkid', card.v.block); yield 0.2; } },
  drum_circle: { hero: 'pebble', name: 'Drum Circle', type: 'attack', cost: 2, rarity: 'rare', art: 'art_crowd', target: 'all', riff: RIFF.long,
    v: { per: 3 }, up: v => { v.per = 4; },
    desc: v => `Long riff. Deal {y}${v.per}{/} to ALL per card played this turn.`,
    effect: function* (c, card, t, r) { yield* c.dealAll(c.riffDamage(card, r, card.v.per * Math.max(1, c.played))); } },
  mud_pie: { hero: 'pebble', name: 'Mud Pie', type: 'skill', cost: 1, rarity: 'common', art: 'art_boulder', target: 'enemy', terrain: 'wet',
    v: { weak: 2 }, up: v => { v.weak = 3; },
    desc: v => `Apply {o}${v.weak}{/} Weak. {s}Touched water this round:{/} to ALL.`,
    effect: function* (c, card, t) { const who = c.touchedAny('wet') ? c.alive() : [t]; for (const e of who) c.applyEnemy(e, 'weak', card.v.weak); yield 0.2; } },
  sugar_crash: { hero: 'pebble', name: 'Sugar Crash', type: 'attack', cost: 0, rarity: 'uncommon', art: 'art_star', target: 'enemy', exhaust: true,
    v: { dmg: 14 }, up: v => { v.dmg = 20; },
    desc: (v, c) => `Deal {y}${Cards.dmg(v.dmg, c)}{/}. You can't play any more cards this turn. Exhaust.`,
    effect: function* (c, card, t) { yield* c.dealDamage(t, card.v.dmg, { heavy: true }); c.flags.crashed = true; } },
  pebble_storm: { hero: 'pebble', name: 'PEBBLE STORM', type: 'attack', cost: 1, rarity: 'rare', art: 'art_boulder', target: 'all',
    v: { dmg: 2, hits: 6 }, up: v => { v.hits = 8; },
    desc: (v, c) => `Throw everything. {y}${Cards.dmg(v.dmg, c)}{/} damage to a random beast ${v.hits} times.`,
    effect: function* (c, card) { for (let i = 0; i < card.v.hits; i++) { const e = c.randomEnemy(); if (!e) break; yield* c.dealDamage(e, card.v.dmg, { projectile: true, quick: true }); } } },

  // ================================================================= ROXY
  splash: { hero: 'roxy', name: 'Splash', type: 'attack', cost: 1, rarity: 'starter', art: 'art_wave', target: 'enemy', el: 'water',
    v: { dmg: 4, soak: 2 }, up: v => { v.dmg = 6; v.soak = 3; },
    desc: (v, c) => `{b}Water.{/} Deal {y}${Cards.dmg(v.dmg, c)}{/}. Apply {b}${v.soak} Soak{/}.`,
    effect: function* (c, card, t) { yield* c.dealDamage(t, card.v.dmg, { projectile: true, el: 'water' }); if (t.alive) c.applyEnemy(t, 'soak', card.v.soak); } },
  zap: { hero: 'roxy', name: 'Zap', type: 'attack', cost: 1, rarity: 'starter', art: 'art_bolt', target: 'enemy', el: 'lightning', riff: RIFF.easy,
    v: { dmg: 6 }, up: v => { v.dmg = 9; },
    desc: (v, c) => `{y}Lightning.{/} Riff. Deal {y}${Cards.dmg(v.dmg, c)}{/}, double to a Soaked beast.`,
    effect: function* (c, card, t, r) { yield* c.dealDamage(t, c.riffDamage(card, r), { el: 'lightning' }); } },
  gust: { hero: 'roxy', name: 'Gust', type: 'skill', cost: 1, rarity: 'starter', art: 'art_spiral', target: 'self', el: 'wind',
    v: { block: 5, draw: 1 }, up: v => { v.block = 7; },
    desc: v => `{c}Wind.{/} Gain {b}${v.block}{/} Block. Draw ${v.draw}.`,
    effect: function* (c, card) { c.gainBlock(card.v.block); c.drawCards(card.v.draw); AudioSys.sfx('whoosh'); yield 0.12; } },
  spark: { hero: 'roxy', name: 'Spark', type: 'attack', cost: 0, rarity: 'starter', art: 'art_star', target: 'enemy', el: 'lightning',
    v: { dmg: 3 }, up: v => { v.dmg = 5; },
    desc: (v, c) => `{y}Lightning.{/} Deal {y}${Cards.dmg(v.dmg, c)}{/}, double to a Soaked beast.`,
    effect: function* (c, card, t) { yield* c.dealDamage(t, card.v.dmg, { projectile: true, el: 'lightning' }); } },
  thunderclap: { hero: 'roxy', name: 'Thunderclap', type: 'attack', cost: 2, rarity: 'uncommon', art: 'art_bolt', target: 'all', el: 'lightning', riff: RIFF.med,
    v: { dmg: 10 }, up: v => { v.dmg = 14; },
    desc: (v, c) => `{y}Lightning.{/} Riff. Deal {y}${Cards.dmg(v.dmg, c)}{/} to ALL, double to Soaked beasts.`,
    effect: function* (c, card, t, r) { Juice.flash('#ffffff', 0.5, 4); AudioSys.sfx('thunder'); yield* c.dealAll(c.riffDamage(card, r), { el: 'lightning' }); } },
  monsoon: { hero: 'roxy', name: 'Monsoon', type: 'skill', cost: 1, rarity: 'common', art: 'art_wave', target: 'all', el: 'water',
    v: { soak: 2 }, up: v => { v.soak = 3; },
    desc: v => `{b}Water.{/} Apply {b}${v.soak} Soak{/} to ALL.`,
    effect: function* (c, card) { AudioSys.sfx('splash'); for (const e of c.alive()) c.applyEnemy(e, 'soak', card.v.soak); yield 0.25; } },
  wildfire: { hero: 'roxy', name: 'Wildfire', type: 'attack', cost: 2, rarity: 'common', art: 'art_fire', target: 'enemy', el: 'fire', terrain: 'hot',
    v: { dmg: 8, burn: 4 }, up: v => { v.dmg = 11; },
    desc: (v, c) => `{o}Fire.{/} Deal {y}${Cards.dmg(v.dmg, c)}{/}, apply {o}${v.burn} Burn{/}. {s}Touched hot ground:{/} double the Burn.`,
    effect: function* (c, card, t) { yield* c.dealDamage(t, card.v.dmg, { fire: true, el: 'fire' }); if (t.alive) c.applyEnemy(t, 'burn', card.v.burn * (c.touchedAny('hot') ? 2 : 1)); } },
  whirlwind: { hero: 'roxy', name: 'Whirlwind', type: 'attack', cost: 1, rarity: 'common', art: 'art_spiral', target: 'all', el: 'wind',
    v: { dmg: 3, hits: 2 }, up: v => { v.dmg = 5; },
    desc: (v, c) => `{c}Wind.{/} Deal {y}${Cards.dmg(v.dmg, c)}{/} to ALL, ${v.hits} times.`,
    effect: function* (c, card) { AudioSys.sfx('whoosh'); for (let i = 0; i < card.v.hits; i++) yield* c.dealAll(card.v.dmg); } },
  ball_lightning: { hero: 'roxy', name: 'Ball Lightning', type: 'attack', cost: 1, rarity: 'common', art: 'art_bolt', target: 'enemy', el: 'lightning',
    v: { dmg: 8 }, up: v => { v.dmg = 11; },
    desc: (v, c) => `{y}Lightning.{/} Deal {y}${Cards.dmg(v.dmg, c)}{/}, double to a Soaked beast.`,
    effect: function* (c, card, t) { yield* c.dealDamage(t, card.v.dmg, { projectile: true, el: 'lightning' }); } },
  rain_song: { hero: 'roxy', name: 'Rain Song', type: 'power', cost: 1, rarity: 'uncommon', art: 'art_flute', target: 'self', el: 'water',
    v: { soak: 1 }, up: v => { v.soak = 2; },
    desc: v => `Start of turn: {b}${v.soak} Soak{/} on every beast.`,
    effect: function* (c, card) { c.addPower('rain', card.v.soak); yield 0.2; } },
  steam: { hero: 'roxy', name: 'Steam', type: 'attack', cost: 1, rarity: 'uncommon', art: 'art_fire', target: 'enemy', el: 'fire',
    v: { per: 6 }, up: v => { v.per = 8; },
    desc: v => `{o}Fire.{/} Boil off every Soak on it: {y}${v.per}{/} damage per Soak.`,
    effect: function* (c, card, t) { const n = t.st.soak || 0; t.st.soak = 0; AudioSys.sfx('sizzle'); yield* c.dealDamage(t, Math.max(3, card.v.per * n), { fire: true, heavy: n > 2 }); } },
  flash_flood: { hero: 'roxy', name: 'Flash Flood', type: 'attack', cost: 3, rarity: 'rare', art: 'art_wave', target: 'all', el: 'water', riff: RIFF.long,
    v: { dmg: 10, soak: 4 }, up: v => { v.dmg = 14; },
    desc: (v, c) => `{b}Water.{/} Long riff. Deal {y}${Cards.dmg(v.dmg, c)}{/} to ALL and apply {b}${v.soak} Soak{/} to ALL.`,
    effect: function* (c, card, t, r) { AudioSys.sfx('splash'); yield* c.dealAll(c.riffDamage(card, r), { el: 'water' }); for (const e of c.alive()) c.applyEnemy(e, 'soak', card.v.soak); } },
  tailwind: { hero: 'roxy', name: 'Tailwind', type: 'skill', cost: 0, rarity: 'common', art: 'art_spiral', target: 'self', el: 'wind', exhaust: true,
    v: { draw: 2 }, up: v => { v.draw = 3; },
    desc: v => `{c}Wind.{/} Draw ${v.draw}. Exhaust.`,
    effect: function* (c, card) { c.drawCards(card.v.draw); AudioSys.sfx('whoosh'); yield 0.1; } },
  ice_shard: { hero: 'roxy', name: 'Ice Shard', type: 'attack', cost: 1, rarity: 'uncommon', art: 'art_star', target: 'enemy', el: 'water', terrain: 'ice',
    v: { dmg: 7 }, up: v => { v.dmg = 10; },
    desc: (v, c) => `{b}Water.{/} Deal {y}${Cards.dmg(v.dmg, c)}{/}. {s}Touched ice this round:{/} double, and apply 1 Soak.`,
    effect: function* (c, card, t) { const ice = c.touchedAny('ice'); yield* c.dealDamage(t, card.v.dmg * (ice ? 2 : 1), { projectile: true, el: 'water' }); if (ice && t.alive) c.applyEnemy(t, 'soak', 1); } },
  storm_caller: { hero: 'roxy', name: 'Storm Caller', type: 'power', cost: 2, rarity: 'rare', art: 'art_moon', target: 'self', el: 'lightning',
    v: { pct: 50 }, up: v => { v.cost = 1; },
    desc: v => `Your {y}Lightning{/} deals {y}${v.pct}%{/} more.`,
    effect: function* (c, card) { c.addPower('storm', card.v.pct / 100); yield 0.2; } },
  puddle_jump: { hero: 'roxy', name: 'Puddle Jump', type: 'skill', cost: 1, rarity: 'common', art: 'art_foot', target: 'self', el: 'water', terrain: 'wet',
    v: { block: 6, energy: 1 }, up: v => { v.block = 9; },
    desc: v => `Gain {b}${v.block}{/} Block. {s}Touched water this round:{/} gain {c}${v.energy}{/} Energy.`,
    effect: function* (c, card) { c.gainBlock(card.v.block); if (c.touchedAny('wet')) c.gainEnergy(card.v.energy); yield 0.12; } },
});

// ---------------------------------------------------------------- artifacts
// The heroes' own, and the ones that care what you walked on.
Object.assign(RELICS, {
  rib_axe: { name: 'The Rib-Axe', tier: 'starter', spr: 'relic_rib_axe', hero: 'bronk', desc: "Bronk's guitar. Start every fight with {r}3 Rage{/}.",
    onCombatStart: c => c.gainRage(3, true) },
  sabre_pendant: { name: 'Sabre Pendant', tier: 'starter', spr: 'relic_sabre', hero: 'vela', desc: 'Whenever you apply Weak or Vulnerable, gain {b}2{/} Block.' },
  skull_bongos: { name: 'Skull Bongos', tier: 'starter', spr: 'relic_bongos', hero: 'pebble', desc: 'Every {y}3rd{/} card you play in a turn hits a random beast for {y}4{/}.' },
  wet_feet: { name: 'Wet Feet', tier: 'starter', spr: 'relic_wet_feet', hero: 'roxy', desc: 'If you touched a {b}wet tile{/} this round, your next {y}Lightning{/} attack deals {y}2x{/} damage.' },
  // walking artifacts: they read what you stepped on this round
  moss_boots: { name: 'Moss Boots', tier: 'common', spr: 'relic_moss_boots', desc: 'Spike pits on {g}grass{/} cannot hurt you, and every grass tile you walk over heals {g}1{/}.', board: true },
  coal_sandals: { name: 'Coal Sandals', tier: 'uncommon', spr: 'relic_sandals', desc: '{o}Hot{/} ground does not burn you. Touched hot ground this round? Start fights with {r}2 Strength{/}.',
    onCombatStart: c => { if (c.touchedAny('hot')) c.applyPlayer('str', 2, true); } },
  bone_rattle: { name: 'Bone Rattle', tier: 'common', spr: 'relic_rattle', desc: 'Every {s}bone tile{/} you touched this round is {b}4 Block{/} at the start of a fight.',
    onCombatStart: c => { const n = c.touched.bone || 0; if (n) c.gainBlock(4 * n); } },
  cave_crystal: { name: 'Cave Crystal', tier: 'uncommon', spr: 'relic_crystal', desc: 'Touched a {p}cave{/} this round? {c}+1 Energy{/} on your first turn.',
    onCombatStart: c => { if (c.touchedAny('dark')) c.energyBonus = (c.energyBonus || 0) + 1; } },
  ice_skates: { name: 'Bone Skates', tier: 'uncommon', spr: 'relic_skates', desc: 'You can stop on {c}ice{/} instead of sliding. Touched ice this round? Draw {y}2{/} more on turn one.',
    onCombatStart: c => { if (c.touchedAny('ice')) c.drawBonus = (c.drawBonus || 0) + 2; } },
  sand_pouch: { name: 'Sand Pouch', tier: 'common', spr: 'relic_sand', desc: 'Touched {y}sand{/} this round? Throw it: every beast starts the fight with {o}1 Weak{/}.',
    onCombatStart: c => { if (c.touchedAny('sand')) for (const e of c.alive()) c.applyEnemy(e, 'weak', 1, true); } },
  lucky_dodo: { name: "Dodo's Foot", tier: 'uncommon', spr: 'relic_dodo_foot', desc: 'Your die never rolls a {y}1{/}. It never did the dodo any good, either.', board: true },
  map_stone: { name: 'Map Stone', tier: 'common', spr: 'relic_map', desc: 'Secrets and mysteries within {y}6 tiles{/} always show what they are.', board: true },
  leaf_cloak: { name: 'Leaf Cloak', tier: 'common', spr: 'relic_leaf', desc: 'Roaming beasts cannot see you on {g}grass{/} or {y}sand{/}, and move 1 tile slower.', board: true },
  thunder_egg: { name: 'Thunder Egg', tier: 'rare', spr: 'relic_thunder', desc: 'Every {b}wet{/} tile you touched this round deals {y}4{/} lightning damage to all beasts when a fight starts.',
    onCombatStart: function* (c) { const n = c.touched.wet || 0; if (!n) return; AudioSys.sfx('thunder'); Juice.flash('#ffffff', 0.4, 4); yield 0.2; for (const e of c.alive()) c.damageEnemy(e, 4 * n, { src: 'relic' }); yield 0.3; } },
  grandmas_glasses: { name: "Grandma's Spare Glasses", tier: 'boss', spr: 'relic_glasses', desc: 'You can see every tile on the board for what it is. Beasts start fights {o}Vulnerable{/}.', board: true,
    onCombatStart: c => { for (const e of c.alive()) c.applyEnemy(e, 'vuln', 1, true); } },
  tar_crown: { name: 'Tar Crown', tier: 'boss', spr: 'relic_crown', desc: 'Tar pits cannot stop you. {c}+1 Energy{/} every turn.', mods: { energy: 1 }, board: true },
  horace_horn: { name: "Horace's Horn", tier: 'boss', spr: 'relic_horace', desc: 'Start every fight with {b}12 Block{/}. Roaming beasts are scared of you.',
    onCombatStart: c => c.gainBlock(12), board: true },
  blaze_ember: { name: "Blaze's Ember", tier: 'boss', spr: 'relic_ember', desc: 'Start of combat: {o}3 Burn{/} on every beast. Your fire cards burn 2 longer.',
    onCombatStart: c => { for (const e of c.alive()) c.applyEnemy(e, 'burn', 3, true); } },
  frost_fang: { name: 'Frostfang', tier: 'boss', spr: 'relic_frostfang', desc: 'The first beast to act each fight is {c}Stunned{/} instead.',
    onCombatStart: c => { const e = c.alive()[0]; if (e) c.stun(e, 1); } },
});
