"""Writes js2/art_board.js: everything the board game added - tile icons,
charms, artifacts, the dinner table's centrepiece, the privy and Grandma
Rex herself - and keeps the manifest honest.
Run it from anywhere: python3 tools/board/build.py"""
import os, sys, json, importlib
D = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(D, '..', '..'))
sys.path.insert(0, D)

def emit(name, frames, outline=True):
    body = ',\n'.join('[\n' + ',\n'.join("'%s'" % r for r in f) + ']' for f in frames)
    return "SPRITES.%s = { %sframes: [\n%s]};\n" % (name, 'outline: true, ' if outline else '', body)

parts = {}
for mod in ['icons', 'props', 'grandma']:
    try:
        m = importlib.import_module(mod)
    except ModuleNotFoundError as e:
        if e.name == mod: continue
        raise
    parts.update(m.build())
out = ["""'use strict';
// art_board.js - GENERATED by tools/board/build.py - edit the generators,
// not this file. Tile icons, charms, artifacts, the roast on the table, the
// privy in the yard, and Grandma Rex.

"""]
for k, v in parts.items(): out.append(emit(k, v, True))
open(os.path.join(ROOT, 'js2/art_board.js'), 'w').write('\n'.join(out))
man = json.load(open(os.path.join(ROOT, 'js2/manifest.json')))
for k, v in parts.items():
    man[k] = dict(w=len(v[0][0]), h=len(v[0]), frames=len(v), file='art_board', note=man.get(k, {}).get('note', 'board game art'))
json.dump(man, open(os.path.join(ROOT, 'js2/manifest.json'), 'w'), indent=1)
print('wrote %d sprites' % len(parts))
