"""Writes js2/art_chars.js: every person in the game, from tools/chars/family.py.
Run it from anywhere:  python3 tools/chars/build.py"""
import os, sys, json
D = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(D, '..', '..'))
sys.path.insert(0, D)
import family

def emit(name, frames):
    body = ',\n'.join('[\n' + ',\n'.join("'%s'" % r for r in f) + ']' for f in frames)
    return "SPRITES.%s = { outline: true, frames: [\n%s]};\n" % (name, body)

S = family.build()
for k, fr in S.items():
    w, h = len(fr[0][0]), len(fr[0])
    for i, f in enumerate(fr):
        assert len(f) == h and all(len(r) == w for r in f), (k, i)
out = ["""'use strict';
// art_chars.js - the Rockbottoms and their neighbours. GENERATED by
// tools/chars/build.py from tools/chars/family.py - edit the generator.
// Every sprite is outline:true: the engine grows the ink, the art draws none.

"""]
for k, v in S.items(): out.append(emit(k, v))
open(os.path.join(ROOT, 'js2/art_chars.js'), 'w').write('\n'.join(out))
man = json.load(open(os.path.join(ROOT, 'js2/manifest.json')))
for k in [k for k, v in man.items() if v.get('file') == 'art_chars' and k not in S]: del man[k]
for k, v in S.items():
    man[k] = dict(w=len(v[0][0]), h=len(v[0]), frames=len(v), file='art_chars', note=man.get(k, {}).get('note', 'person'))
json.dump(man, open(os.path.join(ROOT, 'js2/manifest.json'), 'w'), indent=1)
print('wrote %d sprites' % len(S))
