"""Writes js2/art_home.js: the Rockbottoms' furniture and fittings, and keeps
the manifest honest. Run it from anywhere: python3 tools/home/build.py"""
import os, sys, json
D = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(D, '..', '..'))
sys.path.insert(0, D)
import furniture

def emit(name, frames):
    body = ',\n'.join('[\n' + ',\n'.join("'%s'" % r for r in f) + ']' for f in frames)
    return "SPRITES.%s = { outline: true, frames: [\n%s]};\n" % (name, body)

F = furniture.build()
out = ["""'use strict';
// art_home.js - the cave home, furnished. GENERATED by tools/home/build.py -
// edit the generators, not this file. Lit from the upper left like everything
// else, and every piece gets the engine's ink outline.

"""]
for k, v in F.items(): out.append(emit(k, v))
open(os.path.join(ROOT, 'js2/art_home.js'), 'w').write('\n'.join(out))
man = json.load(open(os.path.join(ROOT, 'js2/manifest.json')))
for k, v in F.items():
    man[k] = dict(w=len(v[0][0]), h=len(v[0]), frames=len(v), file='art_home',
                  note=man.get(k, {}).get('note', 'home furniture'))
json.dump(man, open(os.path.join(ROOT, 'js2/manifest.json'), 'w'), indent=1)
print('wrote %d pieces' % len(F))
