"""Writes js2/art_chars.js from the caveman generator.

Every human sprite in the game is produced here, so a change to cavegen.py's
face, fur or hair shows up on the whole cast at once. Sizes are read from the
manifest and each frame is checked against it, then the whole animation is
centred horizontally and dropped to the bottom of its box so it stands on the
floor line.

    python3 tools/gen_chars.py
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from cavegen import CAST, CLIPS, build, drive_frames, sleep_frames, trim

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAN = json.load(open(os.path.join(ROOT, 'js2/manifest.json')))

# name -> (cast member, clip) in the order they should appear in the file
SHEET = [
    ('bronk_idle', 'bronk', 'idle'), ('bronk_walk', 'bronk', 'walk'),
    ('bronk_eat', 'bronk', 'eat'), ('bronk_play', 'bronk', 'play'),
    ('bronk_shock', 'bronk', 'shock'), ('bronk_drive', 'bronk', '@drive'),
    ('bronk_hurt', 'bronk', 'hurt'),
    ('vela_idle', 'vela', 'idle'), ('vela_walk', 'vela', 'walk'),
    ('vela_cook', 'vela', 'cook'), ('vela_cry', 'vela', 'cry'),
    ('kid_a_idle', 'kid_a', 'idle'), ('kid_a_walk', 'kid_a', 'walk'), ('kid_a_eat', 'kid_a', 'eat'),
    ('kid_b_idle', 'kid_b', 'idle'), ('kid_b_walk', 'kid_b', 'walk'), ('kid_b_eat', 'kid_b', 'eat'),
    ('villager_idle', 'villager', 'idle'), ('villager_walk', 'villager', 'walk'),
    ('villager2_idle', 'villager2', 'idle'), ('villager2_walk', 'villager2', 'walk'),
    ('elder_idle', 'elder', 'idle'),
    ('brute_idle', 'brute', 'idle'), ('brute_walk', 'brute', 'walk'),
    ('bronk_dash', 'bronk', 'dash'),
    ('bronk_sleep', 'bronk', '@sleep'),
    ('bronk_sing', 'bronk', 'sing'),
]

PROBLEMS = []

def fit(frames, w, h):
    """pad/crop every frame to w x h, keeping the figure centred and footed"""
    out = []
    for rows in frames:
        rows = [r[:] for r in rows]
        rows = [r + '.' * max(0, w - len(r)) for r in rows]
        out.append(rows)
    # vertical: bottom-align the tallest, pad the rest
    hh = max(len(r) for r in out)
    if hh > h: PROBLEMS.append('too tall: %d > %d' % (hh, h))
    out = [['.' * w] * (h - len(f)) + [r[:w] for r in f] for f in out]
    # horizontal: one shift for the whole animation so it does not slide
    def bounds(fs):
        lo, hi = 10 ** 6, -1
        for f in fs:
            for r in f:
                for x, c in enumerate(r):
                    if c != '.':
                        lo = min(lo, x); hi = max(hi, x)
        return lo, hi
    lo, hi = bounds(out)
    dx = ((w - 1 - hi) - lo) // 2
    if dx > 0: dx = min(dx, w - 1 - hi)
    elif dx < 0: dx = max(dx, -lo)
    if dx:
        out = [[('.' * dx + r)[:w] if dx > 0 else (r[-dx:] + '.' * -dx) for r in f] for f in out]
    return out

def frames_for(cast, clip, w, h, want):
    if clip == '@drive': fr = drive_frames(cast)
    elif clip == '@sleep': fr = sleep_frames(cast)
    else: fr = [build(cast, p) for p in CLIPS[clip]]
    if len(fr) < want: fr = (fr * want)[:want]
    if len(fr) > want: fr = fr[:want]
    fr = [trim(f) for f in fr]
    return fit(fr, w, h)

head = """'use strict';
// art_chars.js - the family and the villagers, every one of them generated by
// tools/cavegen.py. Big cartoon heads, black dot eyes, dash brows and a mouth
// that drops the jaw off the chin. Regenerate with:  python3 tools/gen_chars.py
// Every sprite is outline:true - the engine grows the dark border, we draw none.

"""
parts = [head]
for name, cast, clip in SHEET:
    m = MAN.get(name)
    if not m:
        PROBLEMS.append('%s not in manifest' % name); continue
    fr = frames_for(cast, clip, m['w'], m['h'], m.get('frames', 1))
    body = ',\n'.join('[\n' + '\n'.join("'%s'," % r for r in f) + '\n]' for f in fr)
    parts.append('SPRITES.%s = { outline: true, frames: [%s]};\n\n' % (name, body))

open(os.path.join(ROOT, 'js2/art_chars.js'), 'w').write(''.join(parts))
print('wrote %d sprites' % (len(parts) - 1))
for p in PROBLEMS: print('  !!', p)
